/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/Details/post': RouteRecordInfo<'/Details/post', '/Details/post', Record<never, never>, Record<never, never>>,
    '/Details/product': RouteRecordInfo<'/Details/product', '/Details/product', Record<never, never>, Record<never, never>>,
    '/donate': RouteRecordInfo<'/donate', '/donate', Record<never, never>, Record<never, never>>,
    '/galery': RouteRecordInfo<'/galery', '/galery', Record<never, never>, Record<never, never>>,
    '/news': RouteRecordInfo<'/news', '/news', Record<never, never>, Record<never, never>>,
    '/result': RouteRecordInfo<'/result', '/result', Record<never, never>, Record<never, never>>,
    '/shop': RouteRecordInfo<'/shop', '/shop', Record<never, never>, Record<never, never>>,
  }
}
